# Generated by Django 5.2.9 on 2025-12-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_type', models.CharField(choices=[('website', 'Webseite (URL)'), ('wifi', 'WIFI Zugang'), ('text', 'Freitext')], default='website', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='Webseiten URL')),
                ('ssid', models.CharField(blank=True, max_length=100, null=True, verbose_name='WLAN Name (SSID)')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='WLAN Passwort')),
                ('security', models.CharField(choices=[('WPA', 'WPA/WPA2'), ('WEP', 'WEP'), ('nopass', 'Offen')], default='WPA', max_length=10)),
                ('text_content', models.TextField(blank=True, null=True, verbose_name='Text Inhalt')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Code Farbe')),
                ('bg_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Hintergrund')),
                ('scale', models.IntegerField(default=10, verbose_name='Größe (Skala)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='qr_logos/', verbose_name='Logo (optional)')),
            ],
        ),
    ]
