# Generated by Django 5.2.9 on 2025-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodeentry',
            name='scale',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Größe (Skala)'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='security',
            field=models.CharField(blank=True, choices=[('WPA', 'WPA/WPA2'), ('WEP', 'WEP'), ('nopass', 'Offen')], default='WPA', max_length=10, null=True),
        ),
    ]
