# Generated by Django 5.2.9 on 2025-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0002_alter_qrcodeentry_scale_alter_qrcodeentry_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeentry',
            name='border_size',
            field=models.IntegerField(default=4, verbose_name='Rahmenbreite (Module)'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Text unter Code (z.B. Scan me)'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='module_style',
            field=models.CharField(choices=[('square', 'Klassisch (Quadrate)'), ('dots', 'Modern (Runde Punkte)')], default='square', max_length=20),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='vcard_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='vcard_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Vor- & Nachname'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='vcard_org',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='vcard_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bg_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='qr_logos/'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='qr_type',
            field=models.CharField(choices=[('website', 'Webseite'), ('wifi', 'WLAN / WIFI'), ('text', 'Freitext'), ('vcard', 'Digitale Visitenkarte (vCard)')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='scale',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='security',
            field=models.CharField(blank=True, choices=[('WPA', 'WPA/WPA2'), ('nopass', 'Offen')], default='WPA', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='ssid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
