# Generated by Django 5.2.9 on 2025-12-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0003_qrcodeentry_border_size_qrcodeentry_bottom_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeentry',
            name='bottom_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Text Farbe'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='bottom_text_size',
            field=models.IntegerField(default=30, verbose_name='Schriftgröße'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bg_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Hintergrund'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='border_size',
            field=models.IntegerField(default=4, verbose_name='Rahmen (Module)'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Text unten'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='QR Farbe'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='module_style',
            field=models.CharField(choices=[('square', 'Klassisch (Quadrate)'), ('rounded', 'Abgerundet (Soft)'), ('circle', 'Punkte (Dots)'), ('diamond', 'Diamanten (Gedreht)'), ('stripe_h', 'Streifen (Horizontal)'), ('stripe_v', 'Streifen (Vertikal)')], default='square', max_length=20, verbose_name='Muster-Stil'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='vcard_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='vcard_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='vcard_org',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='vcard_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
