# Generated by Django 5.2.9 on 2025-12-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0004_qrcodeentry_bottom_text_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodeentry',
            name='border_size',
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='frame_style',
            field=models.CharField(choices=[('none', 'Kein Rahmen'), ('simple', 'Einfacher Rand'), ('polaroid', 'Polaroid'), ('phone', 'Smartphone Look'), ('heavy', 'Fetter Rahmen')], default='none', max_length=20, verbose_name='Rahmen Art'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='logo_preset',
            field=models.CharField(choices=[('none', 'Kein / Eigenes Upload'), ('wifi', 'WLAN Symbol'), ('email', 'E-Mail Symbol'), ('whatsapp', 'WhatsApp'), ('link', 'Link / Weltkugel')], default='none', max_length=20, verbose_name='Preset Logo'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bottom_text',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Text Inhalt'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bottom_text_size',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Code Farbe'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='qr_logos/', verbose_name='Eigenes Logo'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='module_style',
            field=models.CharField(choices=[('square', 'Klassisch (Quadrate)'), ('rounded', 'Abgerundet (Soft)'), ('circle', 'Punkte (Dots)'), ('diamond', 'Diamanten'), ('stripe_h', 'Streifen (H)')], default='square', max_length=20, verbose_name='Muster'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='qr_type',
            field=models.CharField(choices=[('website', 'Webseite'), ('wifi', 'WLAN / WIFI'), ('text', 'Freitext'), ('vcard', 'Digitale Visitenkarte')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='scale',
            field=models.IntegerField(default=10),
        ),
    ]
