# Generated by Django 5.2.9 on 2025-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0005_remove_qrcodeentry_border_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeentry',
            name='text_font',
            field=models.CharField(choices=[('arial.ttf', 'Standard (Arial)'), ('roboto.ttf', 'Modern (Roboto)'), ('caveat.ttf', 'Handschrift (Caveat)')], default='arial.ttf', max_length=50, verbose_name='Schriftart'),
        ),
        migrations.AlterField(
            model_name='qrcodeentry',
            name='bottom_text_size',
            field=models.IntegerField(default=35, verbose_name='Schriftgröße'),
        ),
    ]
