# Generated by Django 5.2.9 on 2025-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_gen_app', '0006_qrcodeentry_text_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcodeentry',
            old_name='bg_color',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='qrcodeentry',
            old_name='color',
            new_name='foreground_color',
        ),
        migrations.RemoveField(
            model_name='qrcodeentry',
            name='scale',
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='border',
            field=models.IntegerField(default=4, verbose_name='Rand (Quiet Zone)'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='box_size',
            field=models.IntegerField(default=10, verbose_name='Größe'),
        ),
        migrations.AddField(
            model_name='qrcodeentry',
            name='error_correction',
            field=models.CharField(choices=[('L', 'Low (7%)'), ('M', 'Medium (15%)'), ('Q', 'Quartile (25%)'), ('H', 'High (30%)')], default='H', max_length=2),
        ),
    ]
